namespace Lecture09.Models;

using System;
using System.Collections.Generic;

partial class Order
{
    public Guid Id{get;} = Guid.NewGuid();
    public string CustomerName{get; set;}
    public List<Product> Products{get; set;}= new List<Product>();

    public Order(string customerName)
    {
        if(string.IsNullOrWhiteSpace(customerName))
            throw new ArgumentException("customer name can not be empty");
        
        CustomerName = customerName;
    }
}

//partial classes allow us to split the definition of a class across multiple files.
//we see partial classes commonly used in code generation scenarios, where part of the class is auto-generated by a tool,
// and the other part is manually written by developers.